source "http://rubygems.org"
gem "sinatra"
gem "sinatra-reloader"
gem "thin"
gem "c2dm", :path => "/home/gimite/devel/c2dm"
gem "highline"
gem "em-websocket"
gem "kyotocabinet-ruby"
gem "ripl"
gem "ripl-multi_line"
gem "ripl-irb"
gem "daemons"
